//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÉttermiSzoftver_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnÉttermiSzoftver : DbContext
    {
        public cnÉttermiSzoftver()
            : base("name=cnÉttermiSzoftver")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enSzemely> enSzemelyek { get; set; }
        public virtual DbSet<enEtel> enEtelek { get; set; }
        public virtual DbSet<enMenu> enMenuk { get; set; }
        public virtual DbSet<enRendeles> enRendelesek { get; set; }
    }
}
